version: '3.2'
services:
  lizmap:
    image: jancelin/docker-lizmap:master
    restart: always
    ports:
     - 80:80
     - 443:443
    volumes:
     - qgis:/home
     - var:/var/www/websig/lizmap/var
    depends_on:
      - postgis
      - qgiserver
      - redisD
    entrypoint: >
      bash -c "wget https://cartman.sig.inra.fr/geopoppy/data/geopoppy_pc.zip &&
               unzip geopoppy_pc.zip -d /home &&
               /start.sh"
  qgiserver:
    image: jancelin/qgis-server:2.18LTR
    restart: always
    volumes:
      - qgis:/home  
  redisD:
    image: redis:alpine
    restart: always
    volumes:
      - redis:/data
  postgis:
    image: kartoza/postgis:10.0-2.4
    ports:
      - 5432:5432
    entrypoint: >
      bash -c "wget -N -P / https://raw.githubusercontent.com/jancelin/docker-postgis/master/setup-database.sh &&
               wget -N -P /home https://github.com/jancelin/docker-postgis/raw/master/geopoppy.tar &&
               /docker-entrypoint.sh"
    environment:
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_USER=docker
      - POSTGRES_DBNAME=geopoppy
      - POSTGRES_DUMP=geopoppy.tar
    volumes:
      - postgres:/var/lib/postgresql
    restart: always
  pgadmin4:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:80
    volumes:
      - pgadmin4:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=geopoppy@inra.fr
      - PGADMIN_DEFAULT_PASSWORD=geopoppy 
  portainer:
    image: portainer/portainer
    restart: always
    ports:
     - 9000:9000
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - portainer:/data  
  cloud:
    image: coderaiser/cloudcmd:latest-alpine
    restart: always
    ports:
      - 8000:8000
    volumes:
      - qgis:/mnt/fs   
volumes:
   portainer:
   redis:
   qgis:
   var:
   postgres:
   pgadmin4:

   

