version: '3'
services:

#---Lizmap & Qgis-server-------------

  lizmap:
    image: jancelin/docker-lizmap:3.1.8
    restart: always
    ports:
     - 80:80
     - 443:443
    volumes:
     - /home/lizmap/lizmap_project:/home
     - /home/lizmap/lizmap_var:/var/www/websig/lizmap/var
     - /home/lizmap/tmp:/tmp
    links:
     - qgiserver:qgiserver

##Pensez Ã  changer l'URL WMS dans le back-office de lizmap: http://qgiserver/cgi-bin/qgis_mapserv.fcgi
  qgiserver:
    image: jancelin/qgis-server:2.18LTR
    restart: always
    volumes:
      - /home/lizmap/lizmap_project:/home
    expose:
      - 80
