  nginx:
    image: nginx:1
    volumes:
      - ./lizmap/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./lizmap/lizmap_var/srv_lizmap:/srv/lizmap
  lizmap:
    image: 3liz/lizmap-web-client:3.3.0
    command: 
      - php-fpm
    environment:
      LIZMAP_WPS_URL: http://wps:8080/
      LIZMAP_CACHESTORAGETYPE: sqlite   
      LIZMAP_CACHEREDISDB: '1'
      LIZMAP_USER: '1010'
      LIZMAP_WMSSERVERURL: http://qgiserver:8080/ows/
      LIZMAP_CACHEREDISHOST: redis
      LIZMAP_HOME: /srv/lizmap
      PHP_INI: \r post_max_size = 50M \n
               upload_max_filesize = 10M
#    entrypoint: >
#      sh -c " chown -R 1010:1010 /tmp && /bin/lizmap-entrypoint.sh"
    expose:
      - 9000
    volumes:
      - ./lizmap/projects:/srv/projects
      - ./lizmap/var/lizmap-theme-config:/www/lizmap/var/lizmap-theme-config
      - ./lizmap/var/lizmap-config:/www/lizmap/var/config
      - ./lizmap/var/lizmap-db:/www/lizmap/var/db
      - ./lizmap/www:/www/lizmap/www
      - ./lizmap/var/log/lizmap:/www/lizmap/var/log
      - ./lizmap/qgiscache:/tmp
    restart: unless-stopped    
  qgiserver:
    image: 3liz/qgis-map-server:3.8
    environment:
      PGSERVICEFILE: /srv/etc/pg_service.conf
      QGSRV_CACHE_ROOTDIR: /srv/projects
      QGSRV_SERVER_WORKERS: 4
      QGSRV_CACHE_SIZE: '20'
      QGSRV_LOGGING_LEVEL: DEBUG
      QGSRV_USER: 1000:1000
      ROUTER_HOST: map
      QGSRV_ZMQ_IDENTITY: OWS-SERVER
      QGSRV_ZMQ_INADDR: tcp://*:18080
      QGSRV_ZMQ_MAXQUEUE: 1000
      QGSRV_ZMQ_TIMEOUT: 15000
      LIBGL_DEBUG: verbose glxinfo
    volumes:
      - ./lizmap/projects:/srv/projects
      - ./lizmap/etc:/srv/etc:ro
      - ./lizmap/processing/__workdir__:/srv/data
    restart: unless-stopped
    expose:
      - 8080
      - 18080
  redis:
    image: redis:4
    restart: always
    volumes:
      - ./lizmap/redis4:/data
    expose:
      - 6379
